name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image ubuntu vnc with chromedriver
      uses: seba8719/docker-headless-vnc-container
      with:
        name: seba8719/ubuntu-vnc-chromedriver
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.ubuntu.xfce.vnc

