name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image ubuntu vnc with chromedriver
      run: docker build . --file Dockerfile.ubuntu.xfce.vnc --tag ubuntu-chromedriver:$(date +%s)
