name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the Docker image ubuntu vnc with chromedriver
        run: docker build . --file Dockerfile.ubuntu.xfce.vnc --tag ubuntu-chromedriver:latest
      - name: Tags
        run: |
          docker tag ubuntu-chromedriver ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-vnc-chromedriver:${{ github.sha }}
          docker tag ubuntu-chromedriver ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-vnc-chromedriver:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-vnc-chromedriver:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-vnc-chromedriver:latest
